From ef6bf72cd08d3b831339693c328fab0ab5c4e02e Mon Sep 17 00:00:00 2001
From: Richard Marko <rmarko@redhat.com>
Date: Tue, 11 Dec 2012 12:26:20 +0100
Subject: [ABRT EL6 PATCH 165/197] abrt-python: fix tests not cleaning after
 themselves

---
 src/python-problem/tests/test_api.py   | 4 ++++
 src/python-problem/tests/test_tools.py | 2 ++
 2 files changed, 6 insertions(+)

diff --git a/src/python-problem/tests/test_api.py b/src/python-problem/tests/test_api.py
index 2ae8dbd..c38b734 100755
--- a/src/python-problem/tests/test_api.py
+++ b/src/python-problem/tests/test_api.py
@@ -267,6 +267,8 @@ class ProblemAPITestCase(ProblematicTestCase):
         path = prob.save()
         tools.ok_('runtime-' in path)
 
+        prob.delete()
+
     def test_repr(self):
         prob = self.create_problem()
         ret = repr(prob)
@@ -342,6 +344,8 @@ class ProblemAPITestCase(ProblematicTestCase):
 
         tools.ok_(ident != ident2)
 
+        prob.delete()
+
     def test_problem_types(self):
         for ptype, internal in problem.PROBLEM_TYPES.items():
             class_name = ptype.lower().capitalize()
diff --git a/src/python-problem/tests/test_tools.py b/src/python-problem/tests/test_tools.py
index b440637..d32a09d 100755
--- a/src/python-problem/tests/test_tools.py
+++ b/src/python-problem/tests/test_tools.py
@@ -38,6 +38,8 @@ class ProblemifyTestCase(ProblematicTestCase):
         prob2 = problem.tools.problemify(ident, self.proxy)
         tools.eq_(type(prob2), problem.Unknown)
 
+        prob.delete()
+
 if __name__ == '__main__':
     logging.basicConfig(level=logging.DEBUG)
     unittest.main()
-- 
1.8.2.1

